export const AUTH_CONSTANTS = {
  SALT_ROUNDS: 10,
  MAX_FAILED_ATTEMPTS: 5,
  LOCK_DURATION_MS: 15 * 60 * 1000, // 15 minutes
  REFRESH_TOKEN: 'refresh_token',
  JWT_ACCESS_SECRET_ENV: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET_ENV: 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXPIRES_IN: '15m',
  JWT_REFRESH_EXPIRES_IN: '7d',
} as const;
